### ISSUE TITLE
Dont display dynaform

### ISSUE THREAD

**Issue by jrauda** [tomolimo/processmaker#100]
Hi i was testing this integracion beetween glpi and process maker.

I was check all but i can not make display the form in GLPI.

I send all the setup in a attach.

thank you for your help.

[Process maker.docx](https://github.com/tomolimo/processmaker/files/3898329/Process.maker.docx)

**Comment by jrauda** [comment]
I change the version of database to mysql 5.7.14 and i have the same result

![imagen](https://user-images.githubusercontent.com/7096812/69751502-d9d73800-1114-11ea-8e5a-90cb06a45036.png)

**Comment by jrauda** [comment]
I logged in PM with the user to make the process, i was tried to view the case and give me this error.
![imagen](https://user-images.githubusercontent.com/7096812/69766158-5b8e8c00-113c-11ea-94be-2f443d9f911d.png)

No php errors.

**Comment by tomolimo** [comment]
Hello @jrauda 
The root cause of your issue is that your are using HTTPS for GLPI but not for PM server.
You may check this in you browser error messages (start developer tools in your browser, generally press F12, and check the error message in the console). You may have a message looking like: can't load an HTTP page when called from an HTTPS page.
This is to prevent security holes in the navigation that browsers prevent this kind of loading.
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
See these screen copies:

![image](https://user-images.githubusercontent.com/7569958/69785680-ef05a280-11b8-11ea-8142-2a1512f9a7fb.png)

and:

![image](https://user-images.githubusercontent.com/7569958/69785686-f4fb8380-11b8-11ea-80b4-8c328732299e.png)

**Comment by tomolimo** [comment]
And about your second error message: let's try to fix first issue, and then create a new issue if this is still present, 
Thank you,
Tomolimo

**Comment by jrauda** [comment]
Hi tomolino, thank you very much for your quick answer, the first problem is fixed.  I will continue testing.
