### ISSUE TITLE
Approbation cas processus par responsable de service dans GLPI

### ISSUE THREAD

**Issue by mamina16** [tomolimo/processmaker#144]
Bonjour Tomolio
Merci pour ce beau Projet
Actuellement je suis entrain de le tester
 et a  grâce  a cette magnifique documentation 
j'ai pas eu de problèmes.
Voila ma question est de savoir peut on attribuer automatiquement une tache  au  responsable d'une entité dans glpi.
Autrement dit
 je souhaiterez avoir a chaque fois qu'un utilisateur dans glpi soumet  un cas (une demande interface self service) que cette demande soit approuvée par son responsable

**Comment by tomolimo** [comment]
Hello @mamina16,

Yes, this is possible (we are doing that in a process to get manager approval).
You need to request GLPI DB (SQL query) to fetch the GUID of the manager of the requester. 
The lookup table that gives PM GUID from GLPI ID is glpi_plugin_processmaker_users (fields are id for GLPI user id and pm_users_id for the matching GUID in PM).

So depending where you have stored the manager id, you'll have to join glpi_plugin_processmaker_users with another GLPI table.

For your information: we are doing that via groups and manager of groups.

And then when you'll have the manager GUID, you'll be able to assign this value to the next task, like shown here: https://wiki.processmaker.com/3.2/Tasks#Value_Based_Assignment

Thank you
Regards,
Tomolimo

PS: please post in English so that your question and answer may benefit others.
