### ISSUE TITLE
Incorrect names of parallel tasks. No description.

### ISSUE THREAD

**Issue by kofe88** [tomolimo/processmaker#148]
**Describe the bug**
When creating several parallel tasks, the names of the tasks are swapped. Task descriptions are also not applied.

**Screenshots**

![image](https://user-images.githubusercontent.com/16879167/163127522-39d57449-447b-458b-a8dc-f4f8eb77dd85.png)

![image](https://user-images.githubusercontent.com/16879167/163129774-2bb3d92e-eb56-4368-b4cf-bc63005462e9.png)

processmaker plugin	4.0.11
PM server 	3.3.0-community-RE-1.7
GLPI 9.5.7

[Tutorial_1-3.zip](https://github.com/tomolimo/processmaker/files/8479372/Tutorial_1-3.zip)

**Comment by tomolimo** [comment]
Hello @kofe88 
Did you synch the new tasks of the process in GLPI?
Thank you
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88 Did you synch the new tasks of the process in GLPI? Thank you Regards, Tomolimo

Yes, of course, I synchronize every time there is a change in PM.
I have attached a process file for an example.

**Comment by tomolimo** [comment]
ok, thank you
Could you also give the GLPI version, the PM plugin version and the PM server version you are using?
Thank you
Regards,
Tomolimo

**Comment by kofe88** [comment]
> processmaker plugin 4.0.11
> PM server 3.3.0-community-RE-1.7
> GLPI 9.5.7

Yes,

processmaker plugin 4.0.11
PM server 3.3.0-community-RE-1.7
GLPI 9.5.7

**Comment by tomolimo** [comment]
Hello @kofe88 
I found the root cause: you are using the "Case label" as if it was the Task description (which is not):
![image](https://user-images.githubusercontent.com/7569958/163192058-4c209189-cd5c-4699-97ce-4428c9ee9538.png)
This is used to define the title and the description of the current case. And as you are modifying the case labels within parallel tasks, one can't say the result...

I imagine that what you would like is to insert the task description in the ticket tasks: to do that, you just need to activate the "Insert Task Category comments in Task Description" here:
![image](https://user-images.githubusercontent.com/7569958/163192740-475b76c8-508d-4661-97d9-9675e15947e5.png)
set this option to Yes, and you should have the task description inserted in the GLPI tasks (you need to restart a new case).

Don't forget to clear the "Case Labels" in the task properties in the process.

Here is the process with these modifications:
[Tutorial_1-4.zip](https://github.com/tomolimo/processmaker/files/8481934/Tutorial_1-4.zip)

**Comment by kofe88** [comment]
@tomolimo ,
I tried, then how do I understand the "title" of the current tasks will be empty and the same for everyone?

![image](https://user-images.githubusercontent.com/16879167/163225059-77f6f2e8-8f01-4849-8adb-e6378cc686cb.png)

![image](https://user-images.githubusercontent.com/16879167/163225368-47039c70-0979-4f4f-8069-c1afcd8614aa.png)

![image](https://user-images.githubusercontent.com/16879167/163225436-fbd359cc-92e4-4c1b-8141-6176bea75695.png)

![image](https://user-images.githubusercontent.com/16879167/163225510-6e4f8c75-05d3-489c-8ca1-c9f88b79e274.png)

**Comment by tomolimo** [comment]
Hello @kofe88 
Yes, everyone will have the same case title, and you can change it whenever you want, but it it will be for all the tasks belonging to that case.
It can be changed in the properties of the tasks (it can be static or dynamic via case variables).

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @kofe88 

For additional info, you may check the ProcessMaker wiki:
https://wiki.processmaker.com/3.2/Tasks#CASE_LABELS (but not the part on the parallel tasks as the custom PM server I've released is based on 3.3.0 and not on 3.6.0)
And https://wiki.processmaker.com/3.2/Tasks#UsingVariablesInLabels

Thank you,
Regards,
Tomolimo

**Comment by kofe88** [comment]
> Hello @kofe88
> 
> For additional info, you may check the ProcessMaker wiki: https://wiki.processmaker.com/3.2/Tasks#CASE_LABELS (but not the part on the parallel tasks as the custom PM server I've released is based on 3.3.0 and not on 3.6.0) And https://wiki.processmaker.com/3.2/Tasks#UsingVariablesInLabels
> 
> Thank you, Regards, Tomolimo

Thank you, I understand!
