### ISSUE TITLE
Is it possible to use ProcessMaker as a validation system

### ISSUE THREAD

**Issue by JulesOutin** [tomolimo/processmaker#158]
Hello,

I'm currently creating a form on glpi and I'm looking for a validation system (workflow). I came across your github with the ProcessMaker plugin.
I'd like more information on this plugin and to know if it's possible to use it as a validation system?

Looking forward to your next reply
Best regards

**Comment by tomolimo** [comment]
Hello @JulesOutin 
In order to give you a clear view on the features of this PM server / plugin, here are some use cases (running currently in our company:

1. Quotation (for hardware request) creation, with cost center manager validation (and optional general manager validation) (within Tickets)
2. ERP rights request for new (or existing) users: request for rights evolution (add/revoke rights), validation by cost center manager (and optional validation by general manager) (within Tickets).
3. Phone process; request for new phone/line, request for phone fix, and so on (within Ticket from simplified interface).
4. Decommissioning of server: to priorize, and keep track of IT operations (serial tasks, or // tasks) (within Tickets).
5. Change and Release process: to keep track of changes on IT, and if neccessary switch to CAB decision for MAJOR change (within Changes).
6. Customs part codes (to request coordiantion between different subsidiaries (in different countries): multiple approvals by local responsibles (within Tickets from simplified interface) (2 processes: new and modification).
7. User off boarding (used only in some countries) (within Tickets).

Currently under development:

1. New server request (with ITOps manager approval)
2. ERP urgent modification (with functional leader approval)

You may findmore information here: https://github.com/tomolimo/processmaker/wiki

Thank you,
Regards,
Tomolimo

**Comment by JulesOutin** [comment]
Hi @tomolimo 

Thank you for your quick response.
Where is this plugin in glpi.

Jules

**Comment by tb-killa** [comment]
@tomolimo thanks for this great inside, hope to see this in New Version Release so we could also implement parts of them :)

**Comment by JulesOutin** [comment]
> Hi @tomolimo
> 
> Thank you for your quick response. Where is this plugin in glpi.
> 
> Jules

**Comment by tomolimo** [comment]
> Hi @tomolimo
> Thank you for your quick response. Where is this plugin in glpi.
> Jules

Hello @JulesOutin 
You have to install it like any other plugins in the /plugins/ folder :) not from the marketplace (not yet).
BUT you also have to install a PM server like described in the wiki of the plugin: https://github.com/tomolimo/processmaker/wiki
The PM server is here: https://github.com/tomolimo/processmaker-server and don't forget to follow the wiki of the server itself:  https://github.com/tomolimo/processmaker-server/wiki

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
> @tomolimo thanks for this great inside, hope to see this in New Version Release so we could also implement parts of them :)

Hello @tb-killa 
A new release that will be compliant with GLPI 10 will be released in some weeks (or some days I should say). 
Thank you,
Regards,
Tomolimo
