### ISSUE TITLE
Connecting GLPI to ProcessMaker

### ISSUE THREAD

**Issue by alogez** [tomolimo/processmaker#20]
Tomolimo,
Je ne parviens pas à faire communiquer GLPI avec Processmaker.
L'ensemble des instructions présentes dans le wiki a été respecté, vraisemblablement.

Dans la deuxième portion de configuration, GLPI parvient à communiquer avec le référentiel de Processmaker Server (ie. Liaison GLPI <-> Base Mysql du référentiel PM Server est effective).

Environnement 1 machine : XP Windows 7.
Wamp : wampserver3.0.6_x86_apache2.4.23_mysql5.7.14_php5.6.25-7.0.10
GLPI : 9_1_2
Processmaker Server : processmaker-server-3.0.1.8-RE-1.6.
Plugin : processmaker-3.1.4.zip

Les fichiers joints sont les suivants : 

- fichier hosts
- log GLPI
- log WAMP
- les 2 fichiers de configuration du serveur apache.

Aurai-je oublié un élément?

Aymeric.

[GLPI_php-errors.txt](https://github.com/tomolimo/processmaker/files/995238/GLPI_php-errors.txt)
[hosts.txt](https://github.com/tomolimo/processmaker/files/995240/hosts.txt)
[httpd.conf.txt](https://github.com/tomolimo/processmaker/files/995239/httpd.conf.txt)
[httpd-vhosts.conf.txt](https://github.com/tomolimo/processmaker/files/995242/httpd-vhosts.conf.txt)
[WAMP_php_error.txt](https://github.com/tomolimo/processmaker/files/995241/WAMP_php_error.txt)

**Comment by tomolimo** [comment]
Hello @alogez,

It seems that there is a login problem with PM server, to investigate further, could you post a screen copy of the GLPI Processmaker plugin configuration (in menu 'Setup > General' and in tab 'ProcessMaker')?
And a screen copy of the PM server user list?

Thank you,
Regards,
Tomolimo

PS: 
1. please post in English, so that it can benefit to all
1. please use pseudo on public posts rather than real names.

**Comment by alogez** [comment]
Hello,
The connection from GLPI (v9_1_2) to Processmaker has been established, thanks to this parameter in php.ini  
Il faut activer ce paramètre dans le fichier php.ini.

`always_populate_raw_post_data = -1`


Thanks.

alogez
