### ISSUE TITLE
Self service assignment rule

### ISSUE THREAD

**Issue by shahmilan34** [tomolimo/processmaker#76]
Hi,
I want to assign a task to Group so that any user from that group can claim and work on task.
This functionality is working in Processmaker Server but not in GLPI.
Version: 
Processmaker-Server  Release 3.0.1.8-RE-1.8
GLPI : 9.2.4
Plugin : 3.2.8

![assignmentrules](https://user-images.githubusercontent.com/31683819/43326887-936dae20-91d7-11e8-9be3-55c12df5884b.png)
![processclaim](https://user-images.githubusercontent.com/31683819/43326927-a6853bfe-91d7-11e8-9917-7de72c4caec0.png)
![claim_task_pro](https://user-images.githubusercontent.com/31683819/43326935-ad272fc6-91d7-11e8-81ae-0663b0574e1b.png)

**Comment by shahmilan34** [comment]
Yeah It worked. 👍 
But then i have to make same groups in processmaker server and GLPI containing GLPI users.
Can we sync GLPI Groups to processmaker by some automatic Action, I am also working on this.

Thank you for your response and support.

**Comment by tomolimo** [comment]
Hello
Pmusers cron is doing that job too. 
It's doing copy of GLPI users and groups into PM server. See https://github.com/tomolimo/processmaker/wiki/Automatic-actions
Thank you 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
> those groups did not get displayed in processmaker.

This means that something went wrong 
Check the logs. 

> So why there is option to select one group if all users and groups are getting synced by Automatic Action

This group doesn't need to be created in GLPI. That's the only reason. And in the future, we may delete this option which is only used for convenience.

Regards 
Tomolimo

**Comment by shahmilan34** [comment]
There are no Errors in logs after running pmusers action.

**Comment by shahmilan34** [comment]
Yeah sure.
Thank you

**Comment by tomolimo** [comment]
Hello @shahmilan34 

### Group synchronization issue:
I made test with GLPI 9.2.4 and PM server 3.0.1.8-RE-1.8, like shown below:
![image](https://user-images.githubusercontent.com/7569958/43399738-1b978696-940c-11e8-98b6-f2019eac77b2.png)

I defined a group with two users:
![image](https://user-images.githubusercontent.com/7569958/43399783-37c71782-940c-11e8-8c2f-c960f69cb599.png)

I've launched the pmusers automatic action, and I got the test group and the users to be added to PM, like shown below:
![image](https://user-images.githubusercontent.com/7569958/43400091-0a048f2c-940d-11e8-9969-01e328c80485.png)

Don't forget that a group must be visible to Tasks and must contains "Users" to be synchronized into PM, see: https://github.com/tomolimo/processmaker/wiki/GLPI-groups-are-not-synchronized-into-PM-server

### Missing "Claim this case" button issue:
1. I've created a small process to test this: 
![image](https://user-images.githubusercontent.com/7569958/43401327-2895528e-9410-11e8-8b33-3ec30905c8ea.png)
1. with a small form:
![image](https://user-images.githubusercontent.com/7569958/43401362-454c49e6-9410-11e8-9810-a492d0bf55af.png)
1. and assignments:
![image](https://user-images.githubusercontent.com/7569958/43401422-68a1373a-9410-11e8-974c-06fb13b4f42f.png)
![image](https://user-images.githubusercontent.com/7569958/43401466-8502f724-9410-11e8-99fa-1ca883088229.png)
1. I run it in a newly created ticket:
1. I submitted the first task, and got the second one:
![image](https://user-images.githubusercontent.com/7569958/43401541-b017b832-9410-11e8-8c0f-06842b58750f.png)

Don't forget that your current GLPI connected user (here glpi) must be in the group 'test', otherwise, it will not show the button. Beware if current GLPI user is assigned to a group, you need to logout/login into GLPI to get this group assignement taken into account.

Thank you,
Regards,
Tomolimo

**Comment by shahmilan34** [comment]
Yeah it worked.
I found my mistake, I was not setting Task to 'yes' while creating groups.

Thank you for help, really appreciated

**Comment by tomolimo** [comment]
Hello @shahmilan34 
you're welcome
Thank you
Regards,
Tomolimo
