### ISSUE TITLE
GLPI PM wrong decisions

### ISSUE THREAD

**Issue by momohamed770** [tomolimo/processmaker#99]
HI,
I'm facing some strange issues related to gateways and conditions when running the case from GLPI is not doing the same when running the case from PM.
I'm sure that PM is working normal as I've other GLPI /PM staging servers and tested with the same workflow and works fine.

Have you faced issue like this when using gateways & conditions?

**Comment by tomolimo** [comment]
Hello,
Could you give more details?
I'm aware an issue, but not sure that matches yours. 
Thank you,
Regards,
Tomolimo

**Comment by momohamed770** [comment]
I've a task with a dynaform as the example below (task 1) the form contain a radio button with a question yes/no I've an exclusive gateway that should check if the value of radio button and take a decision to go to task 2 or 3
@@var == '1'
The case is running normally taking the right decision if run from PM and give a wrong decision when run from GLPI

Also I've GLPI/PM staging servers and it is working fine.



![image](https://user-images.githubusercontent.com/56794498/69607628-49bec300-102e-11ea-824b-6e8729c5afff.png)

**Comment by tomolimo** [comment]
Hello @momohamed770 
I remember that the troubles was when there were two gateways, one after another one. This isn't the case here...
So let's take a look at the conditions for the gateway itself. Could you export your process? And send it to my professional email?
Thank you
Regards,
Tommolimo

**Comment by momohamed770** [comment]
I've also other case with two gateways one after another can you share this issue.

**Comment by tomolimo** [comment]
Hello @momohamed770,

To give more details about the issue, see: https://github.com/tomolimo/processmaker/issues/72#issuecomment-458180907 where there is a picture of a process which is running correctly via GLPI and PM, but if the 'Review of evaluations' task is not present (i.e. the gateways are one after another) then routing via GLPI is not correct, even if the routing via PM is correct.
To explain the apparent root cause:
GLPI is using the web service API to request PM to do the routing, and PM is not internally using the same functions, but it uses another set of functions.

I'm going to search for a clean solution:
* either fix the web service API routing function,
* or either try to use the same functions than PM itself


Regards,
Tomolimo

**Comment by momohamed770** [comment]
Thanks, is there any recommendations from GLPI side to use with gateways, conditions and triggers?

**Comment by momohamed770** [comment]
Issue resolved finally after removing the plugin, DB tables and redeploying again.
Also i've started working differently with gateways to eliminate  having 2 gateways after each other.
